# -*- coding: utf-8 -*-
"""GPT-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EFgSOF2s1geZ7hB9QNbEQdIugr0axxb-
"""

import torch
import transformers
from transformers import GPT2LMHeadModel, GPT2Tokenizer

# Load GPT-2 model and tokenizer
model_name = "gpt2"
model = GPT2LMHeadModel.from_pretrained(model_name)
tokenizer = GPT2Tokenizer.from_pretrained(model_name)

import pandas as pd
import re  # For regular expressions

# Load the CSV file
dataset_path = "chit_chat.csv"
df = pd.read_csv(dataset_path)

user_prompts = df['content']

# Function to generate responses and limit to two sentences
def generate_response(prompt, model, tokenizer, max_length=150):
    input_text = prompt + "\n"

    # Encode the input
    inputs = tokenizer.encode(input_text, return_tensors="pt")

    # Generate the response
    outputs = model.generate(
        inputs,
        max_length=max_length,  # Generate a longer response to ensure we get 2 sentences
        num_return_sequences=1,
        pad_token_id=tokenizer.eos_token_id,
        temperature=0.8,        # Adjust for more creativity
        top_k=50,               # Top-k sampling
        top_p=0.85,             # Nucleus sampling
        repetition_penalty=1.2,  # Increase penalty to avoid repetition
        do_sample=True
    )

    # Decode the generated output
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)

    # Remove the user's prompt from the generated response
    response = response[len(prompt):].strip()


    return response

# List to store all generated responses
gpt2_responses = []
# Loop through each user prompt and generate a response
for prompt in user_prompts:
    response = generate_response(prompt, model, tokenizer)
    gpt2_responses.append(response)

# Save the prompts and responses to a CSV file
evaluation_data = pd.DataFrame({
    'Prompt': user_prompts,
    'Response': gpt2_responses
})

# Save to CSV
evaluation_data.to_csv('gpt2_responses.csv', index=False)
print("All responses saved to 'gpt2_responses.csv'")